import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Container from '@/components/Container';
import SessionWrapper from "@/components/AuthWrapper/SessionWrapper";
import { authOptions } from "@/app/api/auth/[...nextauth]/authOptions";
import { ThemeModeScript } from "flowbite-react/components/ThemeModeScript";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GARAGE-HERO Test",
  description: "Generated by create flowbite react",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <SessionWrapper session={session}>
          {/* <Container> */}
          <Toaster position="bottom-center" richColors />
          {children}
          {/* </Container> */}
        </SessionWrapper>
      </body>
    </html>
  );
}
